service: rag-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  main:
    handler: dist/src/lambda.handler
    events:
      - httpApi:         
          method: ANY
          path: /
      - httpApi:
          method: ANY
          path: /{proxy+}

plugins:
  - serverless-offline